#POR PRIMERA VEZ (LIBRERÍAS NECESARIAS EN EQUIPO DE DESARROLLADOR)

#1. DESCARGAR POR PIP LA LIBRERÍA VIRTUALENV
    #1A. VIRTUALENV -UPGRADE

#2. DESCARGA POR PIP LA LIBRERÍA PYINSTALLER
    #2A. PYINSTALLER -UPGRADE

#3. DESCARGA POR PIP LA LIBRERÍA OPENPYXL
    #3A. OPENPYXL -UPGRADE

#4. DESCARGA POR PIP LA LIBRERÍA AUTO_PY_TO_EXE
    #4A. AUTO-PY-TO-EXE -UPGRADE

#PARA CREAR EJECUTABLES

#1. EJECUTAR EL ACTIVATE DE ENV

#2. DESDE CMD EJECUTAR AUTO-PY-TO-EXE (OJO, GUIONES MEDIOS)
    #2A. CAMBIAMOS EL IDIOMA
    #2B. INTRODUCIMOS LA RUTA DEL SCRIPT PRINCIPAL (MAIN())
    #2C. INFORMAMOS DE SI HAY UNO O VARIOS SCRIPTS
    #2D. SELECCIONAMOS SI QUEREMOS QUE SE VEA LA CONSOLA CMD O NO.

#3. LE FACILITAMOS UN ICONO

#4. LE DAMOS LA RUTA DEL RESTO DE SCRIPTS, IMÁGENES, MÚSICA, ETC, ...

#5. PULSAMOS CONVERT

#6. POR DEFECTO LO SACA EN LA CARPETA OUTPUT

#7. HAY QUE AÑADIR A ESTA CARPETA LOS ARCHIVOS EXTERNOS (IMÁGENES, MÚSICA, OTROS SCRIPTS, ETC, ...)

#8. SE PUEDE PROBAR EN ESTAS CONDICIONES

#9. SE PUEDE METER ESTO EN UN USB PARA LLEVAR A CLIENTE

#10. INSTALAR EN LA RAIZ DEL CLIENTE (C:\)

#11. OJO, CREAR UN ACCESO DIRECTO DEL EJECUTABLE

#12. SE PUEDE PROBAR EN CLIENTE EN ESTE MOMENTO.
