#1. IMPORTAMOS LIBRERÍAS NECESARIAS
import keyboard
import pyautogui as pa

#1B. DESACTIVAMOS LA SEGURIDAD DE LA LIBRERÍA AUTOGUI
pa.FAILSAFE= False

#2. LA FUNCIÓN PA.SIZE() NOS DA EL TAMAÑO DE PANTALLA EN PÍXELES
print("TAMAÑO DE PANTALLA:")
print(pa.size())

#3. LA FUNCIÓN PA.POSITION() INFORMA SOBRE LA POSICIÓN ACTUAL DEL PUNTERO DEL RATÓN
print("LA POSICIÓN DEL RATÓN AHORA MISMO ES:")
print(pa.position())

#4. LA FUNCIÓN PA.MOVETO() MUEVE EL RATÓN A LA POSICIÓN QUE LE INDIQUEMOS.
print("MOVEMOS AL RATÓN AL PUNTO 0,0:")
pa.moveTo(x=0, y=0)
input()

print("MOVEMOS AL RATÓN AL PUNTO 50,50:")
pa.moveTo(x=50, y=50)
input()

print("MOVEMOS AL RATÓN AL PUNTO 50,50:")
pa.moveTo(x=50, y=50)
input()

print("MOVEMOS AL RATÓN AL PUNTO 150,150:")
pa.moveTo(x=150, y=150)
input()

#5. HACER UN CLIC FORZAR DOBLE CLICK IZQUIERDO SIMPLE CON LA FUNCIÓN PA.CLICK()
print("HACEMOS CLICK SIMPLE EN TORNO A LA POSICIÓN 0,0:")
pa.moveTo(x=0, y=0)
pa.click(x=1934, y=17)
#pa.click(x=1934, y=17) (OPCIONAL)
input()

#6. LA FUNCIÓN PA.DOUBLECLICK() EJECUTA EL ICONO SOBRE EL QUE ESTÉ SITUADO EL PUNTERO DE RATÓN
print("HACEMOS DOBLE CLICK SIMPLE EN TORNO A LA POSICIÓN DADA:")
pa.doubleClick(x=1934, y=17)
input()

#7. LA FUNCIÓN PA.RIGHTCLICK() EJECUTA BOTÓN DERECHO AL ICONO DONDE SE SITÚE EL PUNTERO DE RATÓN
print("HACEMOS CLICK DERECHO SIMPLE EN TORNO A LA POSICIÓN DADA:")
pa.rightClick(x=1934, y=17)
input()


















