#1. IMPORTAMOS LA LIBRERÍA NUMPY
# LE PONEMOS EL SOBRENOMBRE NP POR ACORTAR CÓDIGO CUANDO LA LLAMEMOS (... AS NP)
import numpy as np
import random

#2. CREAMOS DATOS FIJOS O LOS CAPTURAMOS DE CONSOLA, VENTANA TKINTER, VENTANA
#DINÁMICA, ARCHIVO DE TEXTO PLANO O ALGIUNA TABLA DE UNA BBDD.

#MUY IMPORTANTE, LOS DATOS DEBEN SER COHERENTES, ES DECIR, TODOS DEL MISMO TIPO.
contenido1 = [0, 0, 0]
contenido2 = [1, 0, 0], [0, 0, 1]
contenido3 = [[0, 1, 0], [0, 1, 0]], [[0, 1, 0], [1, 1, 1]]
contenido4 = []

#3. LA FUNCIÓN ARANGE() GENERA DE FORMA ALEATORIA ARRAYS 1D DE VALORES Y DIMENSIONES QUE LE DIGAMOS.
    #LA FUNCIÓN BÁSICA ADMITE DOS PARÁMETROS. EL PRIMERO ES >=VALOR 1 Y EL SEGUNDO CUMPLE <.
a = np.arange(0,90)
print(a)
print()

    #LA FUNCIÓN ARANGE() AVANZADA ADMITE TRES PARÁMETROS, VALOR INICIAL, VALOR FINAL Y PASO ENTRE VALORES.
b = np.arange(0,90, 11)
print(b)
print()

#4. LA FUNCIÓN ZERO() O ONES() GENERA ARRAYS CON CONTENIDO 0 Y LAS DIMENSIONES QUE LE DIGAMOS.
    #LA FUNCIÓN BÁSICA CREA VECTORES O ARRAYS 1D
c = np.zeros(4)
print(c)
d = np.ones(4)
print(d)
e = np.ones(4)
print(e)
print()

    #LA FUNCIÓN BÁSICA CREA MATRICES O ARRAYS 2D
f = np.zeros((3,4))
print(f)
g = np.ones((3,4))
print(g)
h = np.ones((3,4))
print(h)
print()

    #LAS FUNCIONES AVANZADAS PERMITEN REALIZAR OPERACIONES ENTRE ARRAYS.
i = np.array(c + d + e)
print(i)
print()
j = np.array(f + g + h)
print(j)
print()

#5. LA FUNCIÓN RANDOM() CREA UNA MATRIZ CON NÚMEROS ALEATORIOS ENTRE 0 Y 1
k = np.random.random((3,3))
print(k)
print()

#6. LA FUNCIÓN EMPTY() CREA UNA MATRIZ VACÍA CON LAS DIMENSIONES QUE LE DIGAMOS
#A OJOS DEL USUARIO PUEDE SER LO MISMO QUE ZEROS(), PERO SI OPERAMOS CON EL SISTEMA Y LA HEMOS CREADO
#COMO EMPTY, DARÍA ERRORES AL NO DETECTAR VALORES E INTENTAR REAIZAR OPERACIONES
l = np.empty((3,2))
print(l)
print()

#7. LA FUNCIÓN FULL() CREA UNA MATRIZ CON EL VALOR Y DIMENSIONES QUE LE DIGAMOS .
m = np.full((2,2),8)
print(m)
print()

#8. LA FUNCIÓN LINSPACE() CREA UNA MATRIZ 1D ENTRE UN VALOR Y OTRO DEL TAMAÑO QUE LE DIGAMOS.
#NO ES LO MISMO QUE LA ARANGE() DE TRES PARÁMETROS QUE CUANDO LLEGA AL LÍMITE DEJA DE CREAR VALORES.
n = np.linspace(0,2,10)
print(n)
print()

#9. LA FUNCIÓN EYE() E IDENTITY() AYUDAN A CREAR MATRICES IDENTIDAD.
#SE DENOMINA MATRICES IDENTIDAD A AQUELLAS CUALES LA DIAGONAL PRINCIPAL ES 1 Y EL RESTO DE ELEMENTOS ES 0.
o = np.eye(3,3)
print(o)
print()

p = np.eye(2,5)
print(p)
print()

q = np.identity(5)
print(q)




